name: toysell_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  get: ^4.6.5
  page_transition: ^2.1.0
  internet_connection_checker: ^1.0.0+1
  flutter_spinkit: ^5.2.0
  dio: ^5.3.3
  flutter_svg: ^2.0.7
  cached_network_image: ^3.3.0
  animated: ^2.0.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.12
  image_picker: ^1.0.4
  adaptive_dialog: ^1.9.0+2
  lottie: ^2.7.0
  hexcolor: ^3.0.1
  geocoding: ^2.1.1
  pin_code_fields: ^8.0.1
  device_info_plus: ^10.1.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.31.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  flutter_native_splash: ^2.3.4
  intl_phone_number_input: ^0.7.4
  flutter_card_swiper: ^7.0.1
  list_wheel_scroll_view_nls: ^0.0.3
  dotted_border: ^2.1.0
  carousel_slider: ^5.0.0
  http: ^1.2.2
  mime: ^2.0.0
  http_parser: ^4.1.2
  shimmer: ^3.0.0
  flutter_stripe: ^11.3.0
  intl: ^0.20.0
  timeago: ^3.2.2
  flutter_widget_from_html: ^0.15.3
  cloud_firestore: ^4.17.5
  googleapis_auth: ^1.6.0
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  flutter_map: ^8.0.0
  latlong2: ^0.9.1
  webview_flutter_plus: ^0.4.18
  fl_country_code_picker: ^0.0.4
  flutter_local_notifications: ^19.2.1
  icons_launcher: ^3.0.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0
icons_launcher:
  platforms:
    android:
      enable: true
      image_path: "assets/appicon.png"
      notification_image: "assets/appicon.png"
      adaptive_background_image: "assets/appicon.png"
      adaptive_foreground_image: "assets/appicon.png"
      adaptive_round_image: "assets/appicon.png"
    ios:
      enable: true
      image_path: "assets/appicon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/newIcons/
    - assets/
    - config/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 500
